export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    forgotPassword: "/auth/forgot-password",
    logout: "/auth/logout",
    refreshToken: "/auth/refresh-token",
  },
  account: {
    listAccounts: "/account/list-accounts",
    createAccount: "/account/create-account",
    changePassword: "/account/change-password",
    disableAccount: (accountId: string) => `/account/disable-account/${accountId}`,
    enableAccount: (accountId: string) => `/account/enable-account/${accountId}`,
    previewImportAccounts: "/account/preview-import-accounts",
    confirmImportAccounts: "/account/confirm-import-accounts",
    resetAccountPassword: "/account/reset-password",
  },
  route: {
    listRoutes: "/route/list-routes",
    getRoute: (routeId: number) => `/route/get-route/${routeId}`,
    createRoute: "/route/create-route",
    updateRoute: (routeId: number) => `/route/update-route/${routeId}`,
    enableRoute: (routeId: number) => `/route/enable-route/${routeId}`,
    disableRoute: (routeId: number) => `/route/disable-route/${routeId}`,
    previewImportRoutes: "/route/preview-import-routes",
    confirmImportRoutes: "/route/confirm-import-routes",
  },
  station: {
    listStations: "/station/list-stations",
    getStation: (stationId: number) => `/station/get-station/${stationId}`,
    createStation: "/station/create-station",
    updateStation: (stationId: number) => `/station/update-station/${stationId}`,
    enableStation: (stationId: number) => `/station/enable-station/${stationId}`,
    disableStation: (stationId: number) => `/station/disable-station/${stationId}`,
    previewImportStations: "/station/preview-import-stations",
    confirmImportStations: "/station/confirm-import-stations",
  },
  device: {
    listDevices: "/device/list-devices",
    getDevice: (deviceId: number) => `/device/get-device/${deviceId}`,
    createDevice: "/device/create-device",
    updateDevice: (deviceId: number) => `/device/update-device/${deviceId}`,
    enableDevice: (deviceId: number) => `/device/enable-device/${deviceId}`,
    disableDevice: (deviceId: number) => `/device/disable-device/${deviceId}`,
    previewImportDevices: "/device/preview-import-devices",
    confirmImportDevices: "/device/confirm-import-devices",
  },
  transaction: {
    searchTransactions: "/transaction/search-transactions",
    getTransactionDetail: "/transaction/get-transaction-detail",
  },
} as const
